### ISSUE TITLE
Update the docs building scripts

### ISSUE THREAD

**Issue by armantekinalp** [GazzolaLab/PyElastica#233]
**Describe the bug**
Docs are failing.

**To Reproduce**
Please see the [build](https://github.com/GazzolaLab/PyElastica/actions/runs/4264369787/jobs/7422359766)

**Comment by bhosale2** [comment]
We also need to update the build system and scripts for docs. This could be a good reference for generating modern doc-building system:

https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/.readthedocs.yml

**Comment by armantekinalp** [comment]
@bhosale2 suggested this repo as well https://github.com/tp5uiuc/elastica-pipelines

**Comment by bhosale2** [comment]
An update here, @skim0119 has removed the failing Github action test which is probably redundant at this time. This is because first, the repo for that seems outdated, and second, the docs are rendering without any failures. We can modify this as an issue that updates the docs building scripts and thus is low priority.

**Comment by armantekinalp** [comment]
1772679
