### ISSUE TITLE
Issue with varying radius of filament

### ISSUE THREAD

**Issue by davenpi** [GazzolaLab/PyElastica#27]
Hi all, 

I'm trying to simulate a system where the radius should decrease linearly from the base to the tip of the rod. I can add forces and set the environment without any issues but when I run the integrator I can see that all of the radii are NaNs. There is no failure indicated during integration but on post processing the problem is apparent (screenshot + video below). 
<img width="509" alt="var_rad_code" src="https://user-images.githubusercontent.com/49379192/144279110-f20641bc-7280-4817-96e8-4a83d52462b9.png">

https://user-images.githubusercontent.com/49379192/144279151-6833a85c-1a77-46cb-bf77-eb1a70f119d1.mp4

I'm pretty sure it's not an issue with my implementation of forces/torques on the system as I am able to run the code with no problem in the uniform radius case (screenshot and video below). 

<img width="523" alt="const_rad_code" src="https://user-images.githubusercontent.com/49379192/144279190-4aad8062-81db-4889-9a05-1fd230ca09c6.png">

https://user-images.githubusercontent.com/49379192/144279209-e97dbe6f-c24b-46b1-a2c1-bf2e96efe796.mp4

The allocation of rod properties seems to allow for a varying radius and nothing else jumped out to me as the issue. Do you all have any idea what could be going on here?

**Comment by armantekinalp** [comment]
Hi @davenpi,

It looks like there is numerical instability in your simulation. If you look at the uniform rod simulation you can see the oscillation of the rod elements. Changing the rod to the tapered rod make system more unstable and you get the NaNs after you start running the simulation. 

My suggestions are decrease the time-step and increase the nu (dissipation). Also It is not clear from the code you shared but I suggest ramping up the external forces instead directly applying on to the rod at the first time-steps.

**Comment by davenpi** [comment]
Hi @armantekinalp. I appreciate the response. 

I doubled nu, increased the time resolution by a factor of 5, and ramped up the force over the beginning of the simulation, and this is the result. 

https://user-images.githubusercontent.com/49379192/144678577-85662450-0243-4c9c-94d3-7a29ac8b1638.mp4

It's very unclear why there is so much oscillation. Regardless, why do you think this instability should turn into a divergence when the radius varies? Either way the code deals with a radius array so why should adding different numbers inside the array add any extra instability?

**Comment by armantekinalp** [comment]
Instability you are seeing is not related with how code deals with the radius array. Considering you apply same force to the rod; tapering the rod results in decreasing the  elements mass and rigidity, which will allow elements to move more in between integration steps. The straight forward solution might be using very small time-step to resolve this problem. The second approach is to revisit the `forcing` condition you are applying on the rod and make sure you scale applied forces correctly (I don't know what is your forcing condition but maybe scale forces with element mass?).

Coming back to first question, there can be two reasons for instability, one is physical and the other is numerical. 
Physical reasons can be due to your force model is not correct. For example you might be applying large forces which results rod to break. Maybe share your forcing class here, I can feedback. The numerical reasons maybe simulation is not resolved well in spatially (n_elem) and temporally (time-step)  and/or the dissipation in the system is not chosen correctly. 

My suggestions are as follows:
1. I suggest starting the problem with a softer rod, since generally softer systems (reduce E) are numerically more stable.
2. Revisit the forcing class and make sure your parameters are physically correct. For the tapered case rescale the parameters.

**Comment by davenpi** [comment]
Thanks for the suggestions. Here is a screenshot of the original forcing class I used to produce the issue. I don't see anything obviously wrong but would love to hear your feedback!
<img width="841" alt="tanhforce" src="https://user-images.githubusercontent.com/49379192/145867414-d6b627a5-d1cd-405f-ad96-29bbb0962892.png">

In any case I find that I can produce the same issue with a uniform radius rod, the built in UniformTorques class (slightly modified for force ramping), and a Young's modulus 2 orders of magnitude smaller than before. I have 50 elements and am using a sim_dt = 5e-6 instead of the 2.5e-5 in some of the examples. Here are some screenshots

<img width="740" alt="Screen Shot 2021-12-13 at 2 55 41 PM" src="https://user-images.githubusercontent.com/49379192/145879257-7cf55724-1420-464d-bc99-97ed1319b797.png">


<img width="516" alt="Screen Shot 2021-12-13 at 1 27 14 PM" src="https://user-images.githubusercontent.com/49379192/145867759-06cfe86c-0190-4b03-8a01-ff1f2a5fe3fe.png">

<img width="391" alt="Screen Shot 2021-12-13 at 1 28 54 PM" src="https://user-images.githubusercontent.com/49379192/145867979-6a0e68ed-4f9d-4270-911d-1c6c81a2ec5b.png">

https://user-images.githubusercontent.com/49379192/145867994-c5324591-f656-4c0a-86df-5c308b9f2e5a.mp4

I will retry with a smaller Young's modulus and simulation dt but I thought you might find these interesting as it seems the issue is more generic than expected. I'm also going to play around with torque magnitudes some more in the interim. You mentioned tuning the damping but I'm not sure how to do that in a principled way. Are you suggesting just increasing it repeatedly and experimenting or is there something else you had in mind?

**Comment by armantekinalp** [comment]
Hi @davenpi ,

Sorry to get back to you late. Did you able to stabilize your simulations, decreasing the Young's modulus help? To increase damping there is no principled way, I start with smaller value and increase it until it stabilizes.

**Comment by armantekinalp** [comment]
I am closing this issue, please reopen the issue if your problem is not resolved.
