### ISSUE TITLE
Visualization bug of lacking Povray

### ISSUE THREAD

**Issue by woshizh951** [GazzolaLab/PyElastica#66]
**Describe the bug**
I want to run the example of snake visualization, the scripting process is running correctly.
However, when the rendering process begin, Some error occured.
File "G:\study\pyelastica\PyElastica-master\examples\Visualization\ContinuumSnakeVisualization\_povmacros.py", line 138, in render
    + stderr.decode("ascii",'ignore')
OSError: POVRay rendering failed with the following error: 'povray' 
By checking the codel, i found that the subprocess is calling povray here, but the povray does not installed in my PC.
I try to install the newest version of povray, but it still can have same error to run the code.
The question is: How I install povray correctly, is any special library i need to install?
please give me a instruction. thank you so much!!

**To Reproduce**
```_povmacros.py
from line 127 to 139
<script>
    process = subprocess.Popen(
        cmds, stderr=subprocess.PIPE, stdin=subprocess.PIPE, stdout=subprocess.PIPE
    )
    _, stderr = process.communicate()

    # # Check execution error
    if process.returncode:
        print(type(stderr), stderr)
        raise IOError(
            "POVRay rendering failed with the following error: "
            + stderr.decode("ascii",'ignore')

        )
<error>
```

**Environment**
- Python/pip version 3.6
- Numpy/numba version 1.19
- PyElastica version 0.1.0 post5
- OS, Device,  Window 10

**Expected behavior**
I hope to run the visualization correctly. And I would like to simulation the manipulation of deformable linear objects(cable)
by the pyelastca, would you please give me some advice?

**Screenshots**

**Additional context**

**Comment by skim0119** [comment]
Hi @woshizh951 

It appears to me that _POVray does not provide CLI_ for `Windows 10` (https://github.com/POV-Ray/povray/issues/227). The script above assumes POVray available on CLI, which is why you are getting an error.

**Suggestion**
1. Remove any `.pov` file created: remove `frames/diag` or `frames/top` directory.
2. Modify https://github.com/GazzolaLab/PyElastica/blob/dd1bff433e7789914939e11eb6db90cfd60eee71/examples/Visualization/ContinuumSnakeVisualization/continuum_snake_render.py#L79-L83
to represent global path. For example
```
    included = ["C:\\Users\\mattia-lab\\Downloads\\PyElastica-master\\examples\\Visualization\\default.inc"]
```
3. run `python continuum_snake_render.py`. It is okay to get an error, as long as `.pov` files are created properly. They should be created in the directory `frames\diag` and `frames\top`.
4. Render `.pov` files on POVray

---

On POVray windows, you can run batch-rendering by pressing `alt-Q`

![image](https://user-images.githubusercontent.com/3798023/157078751-4a3ec006-1d36-4245-93e7-33148a4c3b1d.png)

![image](https://user-images.githubusercontent.com/3798023/157082580-008d4da4-22ea-4d75-8e63-d8425cf96d33.png)

![image](https://user-images.githubusercontent.com/3798023/157083303-f9ec98ae-ebe2-49ca-ac2c-f1709e87e5ae.png)

---

After generating all the frames, you can combine images to make movie. We use `moviepy` in the script to do so:

https://github.com/GazzolaLab/PyElastica/blob/dd1bff433e7789914939e11eb6db90cfd60eee71/examples/Visualization/ContinuumSnakeVisualization/continuum_snake_render.py#L183-L194

**Comment by skim0119** [comment]
I am closing this issue. @woshizh951 Please feel free to reopen this issue or create a new one if you have further questions.

**Comment by woshizh951** [comment]
Thank you so much, i can render the simulation through you tutorial now.
